# Generated by Django 4.1.7 on 2023-05-14 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.CharField(default='', max_length=40)),
                ('city', models.CharField(default='', max_length=40)),
                ('street', models.CharField(default='', max_length=40)),
                ('house', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Classes_room',
            fields=[
                ('number', models.CharField(default='', max_length=20)),
                ('id_build', models.CharField(default='', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='discipline',
            fields=[
                ('department', models.CharField(default='', max_length=20)),
                ('name_of_discipline', models.CharField(default='', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='email_teacher',
            fields=[
                ('email', models.CharField(default='', max_length=20)),
                ('id_teacher', models.CharField(default='', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_of_admission', models.CharField(default='', max_length=40)),
                ('id_headman', models.CharField(default='', max_length=50)),
                ('group_number', models.CharField(default='', max_length=40, null=True)),
                ('direction_information', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_participation', models.CharField(default='', max_length=50)),
                ('id_teacher', models.CharField(default='', max_length=50)),
                ('id_discipline', models.CharField(default='', max_length=50)),
                ('id_audience', models.CharField(default='', max_length=50)),
                ('date_and_time', models.CharField(default='', max_length=40)),
                ('id_type_of_lesson', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson_participants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_group', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surname', models.CharField(default='', max_length=40)),
                ('name', models.CharField(default='', max_length=40)),
                ('patronic', models.CharField(default='', max_length=40, null=True)),
                ('id_group', models.CharField(default='', max_length=40)),
                ('student_book_number', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Phones',
            fields=[
                ('phone', models.CharField(default='', max_length=20)),
                ('id_student', models.CharField(default='', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surname', models.CharField(default='', max_length=40)),
                ('name', models.CharField(default='', max_length=40)),
                ('patronic', models.CharField(default='', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Phones',
            fields=[
                ('phone', models.CharField(default='', max_length=20)),
                ('id_teacher', models.CharField(default='', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='type_of_lessons',
            fields=[
                ('type_of_lessons', models.CharField(default='', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
