# Generated by Django 4.1.7 on 2023-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='id_participation',
        ),
        migrations.AddField(
            model_name='lesson_participants',
            name='id_lesson',
            field=models.CharField(default='', max_length=50),
        ),
    ]
