# Generated by Django 4.1.7 on 2023-05-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_remove_lesson_id_participation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='id_lesson_participants',
            field=models.CharField(default='', max_length=50),
        ),
    ]
