# Generated by Django 4.1.7 on 2023-05-20 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_lesson_id_lesson_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_time',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_even', models.BooleanField()),
                ('index', models.IntegerField()),
                ('day_of_week', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
