# Generated by Django 4.1.7 on 2023-05-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_lesson_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_time',
            name='day_of_week',
            field=models.IntegerField(default='', max_length=50),
        ),
    ]
