# Generated by Django 4.1.7 on 2023-05-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_lesson_participants_id_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes_room',
            name='id_build',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='email_teacher',
            name='id_teacher',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='id_headman',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_and_time',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id_audience',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id_discipline',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id_lesson_participants',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id_teacher',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id_type_of_lesson',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_group',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='student_phones',
            name='id_student',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='teacher_phones',
            name='id_teacher',
            field=models.UUIDField(),
        ),
    ]
