# Generated by Django 4.1.7 on 2023-05-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_alter_classes_room_id_build_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='id_discipline',
            field=models.CharField(default='', max_length=40),
        ),
    ]
