# Generated by Django 4.1.7 on 2023-05-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_lesson_id_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='id_discipline',
            field=models.UUIDField(),
        ),
    ]
