# Generated by Django 4.1.7 on 2023-05-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_alter_lesson_id_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_and_time',
            field=models.CharField(default='', max_length=40),
        ),
    ]
