# Generated by Django 4.1.7 on 2023-05-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_alter_lesson_date_and_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date_and_time',
        ),
    ]
