# Generated by Django 4.1.7 on 2023-05-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_remove_lesson_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date_and_time',
            field=models.CharField(default='', max_length=32),
        ),
    ]
